name: RestraintAuto
views:
    Night:
        T: 6500
        Lsw: 2
        Lmax: 10
        Lb: 6
        bg_hex: "#e8e8e8"
    Day:
        T: 6500
        Lsw: 100
        Lmax: 60
        Lb: 40
        bg_hex: "#e8e8e8"
palette:
    greys:
        type: fixed
        args:
            black: "#000000"
            white: "#ffffff"
            fg: "#3f3f3f"
            fg_grey: "#3f3f3f"
            fg_light: "#808080"
            bg_grey: "#e8e8e8"
            bg_grey_dark: "#d9d9d9"
    salmons:
        type: fixed
        args:
            salmon_dark: "#CCBCAD"
            salmon: "#F2DFCE"
            salmon_hl: "#FFF1E4"
    pri:
        type: tri_hex
        args:
            base_j: 0.37
            pitch: 0.12
            ring0_name: tone
            ring1_name: pri
            ring2_name: ult
            tints_name: tint
    hl:
        type: jab_ring
        args:
            n_colors: 6
            j_lb: 0.83
            j_ub: 0.83
            m_lb: 12.0
            m_ub: 12.0
    bg:
        type: jab_ring
        args:
            n_colors: 6
            j_lb: 0.87
            j_ub: 0.87
            m_lb: 5.0
            m_ub: 5.0
