name: RestraintAuto
views:
    Night:
        T: 6500
        Lsw: 2
        Lmax: 10
        Lb: 6
        bg_hex: "#e8e8e8"
    Day:
        T: 6500
        Lsw: 100
        Lmax: 60
        Lb: 40
        bg_hex: "#e8e8e8"
palette:
    greys:
        type: greys
        args:
            white: 1.00
            bg_light: 0.975
            bg: 0.90
            bg_dark: 0.825
            fg_light: 0.35
            fg: 0.15
            fg_dark: 0.075
            black: 0.00
    salmons:
        type: fixed
        args:
            salmon_dark: "#CCBCAD"
            salmon: "#F2DFCE"
            salmon_hl: "#FFF1E4"
    pri:
        type: tri_hex
        args:
            base_j: 0.37
            pitch: 0.12
            ring0_name: tone
            ring1_name: pri
            ring2_name: ult
            tints_name: tint
    hl:
        type: jab_ring
        args:
            n_colors: 6
            j_lb: 0.83
            j_ub: 0.83
            m_lb: 12.0
            m_ub: 12.0
    bg:
        type: jab_ring
        args:
            n_colors: 6
            j_lb: 0.87
            j_ub: 0.87
            m_lb: 5.0
            m_ub: 5.0
